name: tfsec

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tfsec and generate SARIF
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif

          # Must be STRING, not boolean  
          # "false" â†’ action correctly disables force-all-dirs  
          full_repo_scan: "false"

          working_directory: .

          tfsec_args: >
            --exclude-path .terraform
            --exclude-path examples
            --exclude-path _example

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
