name: tfsec

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tfsec using Docker (no permissions issue)
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) \
            -v "$(pwd)":/src \
            aquasec/tfsec:latest \
            /src \
            --soft-fail \
            --format sarif \
            --out /src/tfsec.sarif \
            --exclude-path .terraform \
            --exclude-path examples \
            --exclude-path _example

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
