name: tfsec

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tfsec using Docker
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) \
            -v "$(pwd)":/src \
            aquasec/tfsec:latest \
            /src \
            --soft-fail \
            --format sarif \
            --out /src/tfsec.sarif

      - name: Upload SARIF to GitHub Code Scanning
        if: github.event.pull_request.head.repo.fork == false
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif

      - name: tfsec PR commenter
        if: github.event_name == 'pull_request'
        uses: tfsec/tfsec-pr-commenter-action@v1.3.1
        with:
          GITHUB_TOKEN: ${{ github.token }}
