name: tfsec

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tfsec and generate SARIF
        uses: aquasecurity/tfsec-action@v1
        with:
          format: sarif
          sarif_file: tfsec.sarif
          working_directory: .
          args: >
            --exclude-path .terraform
            --exclude-path examples
            --exclude-path _example

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
